### ISSUE TITLE
-lpthread apparently absent from cactus/caf/Makefile

### ISSUE THREAD

**Issue by malcook** [ComparativeGenomicsToolkit/cactus#19]
In my hands `-lpthread` must be added to gcc build of cactus_caf and stCafTests else

```
...
cd caf && make all
make[1]: Entering directory `/home/mec/local/src/cactus/caf'
gcc -std=c99 -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG  -I /home/mec/local/src/cactus/submodules/sonLib/lib -I inc -I ../lib// -c impl/*.c
impl/giantComponent.c: In function 'stCaf_breakupComponentGreedily':
impl/giantComponent.c:38:13: warning: variable 'edgeScore' set but not used [-Wunused-but-set-variable]
     int64_t edgeScore = INT64_MAX;
             ^
ar rc stCaf.a *.o
ranlib stCaf.a 
rm *.o
mv stCaf.a ../lib//
cp inc/*.h ../lib//
gcc -std=c99 -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG  -I /home/mec/local/src/cactus/submodules/sonLib/lib -I inc -I impl -I../lib/ -o ../bin//stCafTests tests/*.c impl/*.c ../lib//stCaf.a ../lib//cactusBlastAlignment.a /home/mec/local/src/cactus/submodules/sonLib/lib/stPinchesAndCacti.a /home/mec/local/src/cactus/submodules/sonLib/lib/3EdgeConnected.a ../lib//cactusLib.a /home/mec/local/src/cactus/submodules/sonLib/lib/sonLib.a /home/mec/local/src/cactus/submodules/sonLib/lib/cuTest.a    -lz -lm -lpthread
impl/giantComponent.c: In function 'stCaf_breakupComponentGreedily':
impl/giantComponent.c:38:13: warning: variable 'edgeScore' set but not used [-Wunused-but-set-variable]
     int64_t edgeScore = INT64_MAX;
             ^
gcc -std=c99 -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG  -I /home/mec/local/src/cactus/submodules/sonLib/lib -I inc -I impl -I../lib/ -o ../bin//cactus_caf cactus_caf.c impl/*.c ../lib//stCaf.a ../lib//cactusBlastAlignment.a /home/mec/local/src/cactus/submodules/sonLib/lib/stPinchesAndCacti.a /home/mec/local/src/cactus/submodules/sonLib/lib/3EdgeConnected.a ../lib//cactusLib.a /home/mec/local/src/cactus/submodules/sonLib/lib/sonLib.a /home/mec/local/src/cactus/submodules/sonLib/lib/cuTest.a    -lz -lm
impl/giantComponent.c: In function 'stCaf_breakupComponentGreedily':
impl/giantComponent.c:38:13: warning: variable 'edgeScore' set but not used [-Wunused-but-set-variable]
     int64_t edgeScore = INT64_MAX;
             ^
/home/mec/local/src/cactus/submodules/sonLib/lib/sonLib.a(stThreadPool.o): In function `stThreadPool_construct':
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: undefined reference to `pthread_create'
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: undefined reference to `pthread_create'
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: undefined reference to `pthread_create'
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: undefined reference to `pthread_create'
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: undefined reference to `pthread_create'
/home/mec/local/src/cactus/submodules/sonLib/lib/sonLib.a(stThreadPool.o):/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:144: more undefined references to `pthread_create' follow
/home/mec/local/src/cactus/submodules/sonLib/lib/sonLib.a(stThreadPool.o): In function `stThreadPool_destruct':
/home/mec/local/src/cactus/submodules/sonLib/C/impl/stThreadPool.c:195: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin//cactus_caf] Error 1
make[1]: Leaving directory `/home/mec/local/src/cactus/caf'
make: *** [all.caf] Error 2
```

**Comment by muffato** [comment]
I had the same issue on Ubuntu 14.04 with gcc 4.8.5 and binutils 2.24. but it worked on our cluster (HEL 7.3, gcc 5.4.0 and binutils 2.29.1)
